version: '3.9'
services:
  ddns_client:
    build:
      context: .
      dockerfile: aliyun-ddns/Dockerfile
    restart: unless-stopped
    logging: 
      options: 
        max-size: 100M
        max-file: 1
    environment:
      - AKID=xxx
      - AKSCT=xxx
      - DOMAIN=xxx
      - REDO=60
      - TTL=600
      - TYPE=A
      - CNIPV4=true
    deploy:
      resources:
        limits:
          memory: 128M
